pub const DEFAULT_MIN_TIME_STEP: f32 = 0.0;
pub const DEFAULT_TIME_STEP: f32 = 0.5;
pub const DEFAULT_MAX_TIME_STEP: f32 = 2.0;
pub const DEFAULT_TIME_STEP_STEP: f32 = 0.1;

pub const DEFAULT_DIFFUSION: f32 = 0.5;
pub const DEFAULT_MIN_DIFFUSION: f32 = 0.0;
pub const DEFAULT_MAX_DIFFUSION: f32 = 2.0;
pub const DEFAULT_DIFFUSION_STEP: f32 = 0.1;

pub const DEFAULT_ADDED_DENSITY: f32 = 15.0;
pub const DEFAULT_ADDED_DENSITY_MIN: f32 = 0.0;
pub const DEFAULT_ADDED_DENSITY_MAX: f32 = 40.0;
pub const DEFAULT_ADDED_DENSITY_STEP: f32 = 1.0;

pub const DEFAULT_ADDED_VELOCITY: f32 = 50.0;
pub const DEFAULT_ADDED_VELOCITY_MIN: f32 = 0.0;
pub const DEFAULT_ADDED_VELOCITY_MAX: f32 = 500.0;
pub const DEFAULT_ADDED_VELOCITY_STEP: f32 = 50.0;

pub const CANVAS_ID: &str = "main-canvas";
